routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::group(['prefix' => 'authorization', 'as' => 'authorization.'], function () {
            Route::get('/index', 'AuthorizationController@index')->name('index');
            Route::get('/getItemInfo/{id}', 'AuthorizationController@getItemInfo')->name('getItemInfo');
            Route::get('/changeStatus/{id}', 'AuthorizationController@changeStatus')->name('changeStatus');
        });
    });


    Route::group(['namespace' => 'Guest'], function () {
        Route::get('/patients/order/getItems/{id}', 'PatientController@getItems')->name('delivery.getItems');
        Route::get('/patients/order/getItemDetail/{id}', 'PatientController@getItemDetail')->name('delivery.getItemDetail');
        Route::get('/patients/order/getKitDetail/{id}', 'PatientController@getKitDetail')->name('delivery.getKitDetail');

        Route::get('/home', 'OrdersController@index')->name('home');
        Route::get('/currentOrders', 'OrdersController@index')->name('current_orders');
        Route::get('/currentOrders/cancel/{id}', 'OrdersController@cancel')->name('cancel_order');
        Route::get('/currentOrders/delivery/edit/{id}', 'OrdersController@editOrder')->name('edit_order');

        Route::group(['prefix' => 'patients', 'as' => 'patients.'], function () {
            Route::get('/', 'PatientController@index')->name('index');
            Route::get('/history/{id}', 'PatientController@history')->name('history');
            Route::get('/create', 'PatientController@create')->name('create');
            Route::get('/edit/{id}', 'PatientController@edit')->name('edit');
            Route::post('/store', 'PatientController@store')->name('store');
            Route::post('/update/{id}', 'PatientController@update')->name('update');
            Route::post('/address/store', 'PatientController@storeAddress')->name('address.store');
            Route::post('/address/update', 'PatientController@updateAddress')->name('address.update');
            Route::get('/address/edit/{id}', 'PatientController@editAddress')->name('address.edit');
            Route::post('/medgroup/store', 'PatientController@storeMedGroup')->name('medgroup.store');
            Route::post('/medgroup/update', 'PatientController@updateMedGroup')->name('medgroup.update');
            Route::get('/medgroup/edit/{id}', 'PatientController@editMedGroup')->name('medgroup.edit');
            Route::post('/diagnose/store', 'PatientController@storeDiagnose')->name('diagnose.store');
            Route::get('/diagnose/description/{code}', 'PatientController@getDiagnoseDescription')->name('diagnose.description');
            Route::post('/diagnose/update', 'PatientController@updateDiagnose')->name('diagnose.update');
            Route::get('/diagnose/edit/{id}', 'PatientController@editDiagnose')->name('diagnose.edit');
            Route::get('/diagnose/remove/{id}', 'PatientController@removeDiagnose')->name('diagnose.remove');
            Route::get('/medgroup/remove/{id}', 'PatientController@removeMedgroup')->name('medgroup.remove');
            Route::post('/doctor/store', 'PatientController@storeDoctor')->name('doctor.store');
            Route::get('/doctor/edit/{id}', 'PatientController@editDoctor')->name('doctor.edit');
            Route::post('/doctor/update', 'PatientController@updateDoctor')->name('doctor.update');
            Route::get('/delete/{id}', 'PatientController@delete')->name('delete');
            Route::group(['prefix' => '{patient_id}/order', 'as' => 'order.'], function () {
                Route::get('/pickup/create', 'PatientController@pickupCreate')->name('pickup.create');
                Route::get('/respite/create', 'PatientController@respiteCreate')->name('respite.create');
                Route::get('/move/create', 'PatientController@moveCreate')->name('move.create');
                Route::get('/exchange/create', 'PatientController@exchangeCreate')->name('exchange.create');
                Route::get('/delivery/create', 'PatientController@deliveryCreate')->name('delivery.create');
                Route::get('/delivery/store', 'PatientController@storeDelivery')->name('delivery.store');
                Route::get('/delivery-edit/store', 'OrdersController@updateDelivery')->name('delivery-edit.store');
                Route::get('/delivery/getItems/{id}', 'PatientController@getItems')->name('delivery.getItems');
            });
//            Route::group(['prefix' => 'addresses', 'as' => 'address.'], function (){
//                Route::post('/store', 'PatientController@storeAddress')->name('store');
//                Route::post('/update/{id}', 'PatientController@updateAddress')->name('update');
//            });
//            Route::group(['prefix' => 'doctor', 'as' => 'doctor.'], function (){
//                Route::post('/store', 'PatientController@storeDoctor')->name('store');
//                Route::post('/update/{id}', 'PatientController@updateDoctor')->name('update');
//            });
//            Route::group(['prefix' => 'medGroup', 'as' => 'medgroup.'], function (){
//                Route::post('/store', 'PatientController@storeMedGroup')->name('store');
//                Route::post('/update/{id}', 'PatientController@updateMedGroup')->name('update');
//            });
//            Route::group(['prefix' => 'diagnose', 'as' => 'diagnose.'], function (){
//                Route::post('/store', 'PatientController@storeDiagnose')->name('store');
//                Route::post('/update/{id}', 'PatientController@updateDiagnose')->name('update');
//            });
        });

        Route::group(['prefix' => 'customerCare', 'as' => 'customer_care.'], function () {
            Route::get('/', 'CustomerController@index')->name('index');
            Route::get('/create_concern', 'CustomerController@createConcern')->name('create_concern');
            Route::get('/create_compliment', 'CustomerController@createCompliment')->name('create_compliment');
        });

        Route::group(['prefix' => 'facilities', 'as' => 'facilities.'], function () {
            Route::get('/', 'FacilitiesController@index')->name('index');
            Route::get('/create', 'FacilitiesController@create')->name('create');
            Route::get('/edit/{id}', 'FacilitiesController@edit')->name('edit');
        });

        Route::group(['prefix' => 'nurses', 'as' => 'nurses.'], function () {
            Route::get('/', 'NursesController@index')->name('index');
            Route::get('/create', 'NursesController@create')->name('create');
            Route::get('/edit/{id}', 'NursesController@edit')->name('edit');
            Route::post('/store', 'NursesController@store')->name('store');
            Route::post('/update/{id}', 'NursesController@update')->name('update');
            Route::get('/delete/{id}', 'NursesController@delete')->name('delete');
        });

        Route::get('/account', 'AccountController@index')->name('account');
        Route::get('/resources', 'ResourcesController@index')->name('resources');
    });
});

Route::get('confirmation/{token}', ['uses' => 'Admin\AdminController@changePassword']);

app/Http/Controllers/Guest/AccountController.php
<?php

namespace App\Http\Controllers\Guest;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AccountController extends Controller
{
    public function index()
    {
        return view('guest.account.index');
    }
}

app/Http/Controllers/Guest/CustomerController.php
<?php

namespace App\Http\Controllers\Guest;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CustomerController extends Controller
{
    public function index()
    {
        return view('guest.customerCare.index');
    }

    public function createConcern ()
    {
        return view('guest.customerCare.create_concern');
    }

    public function createCompliment ()
    {
        return view('guest.customerCare.create_compliment');
    }
}

app/Http/Controllers/Guest/FacilitiesController.php
<?php

namespace App\Http\Controllers\Guest;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FacilitiesController extends Controller
{
    public function index()
    {
        return view('guest.facilities.index');
    }

    public function create()
    {
        return view('guest.facilities.create');
    }

    public function edit($id)
    {
        return view('guest.facilities.edit');
    }
}

app/Http/Controllers/Guest/NursesController.php
<?php

namespace App\Http\Controllers\Guest;

use App\Http\Requests\NursesRequest;
use App\Models\Nurses;
use App\Models\NursesInsurance;
use App\Models\PatientDoctor;
use App\Models\State;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use PharIo\Manifest\AuthorCollectionTest;

class NursesController extends Controller
{
    public function index()
    {
        $nurses = Nurses::whereHas('nursesInsurance', function ($query) {
            $query->where('InsuranceID', '=', Auth::user()->insurance->InsuranceID);
        })->get();

        return view('guest.nurses.index', compact('nurses'));
    }

    public function create()
    {
        $states = State::pluck('StateName', 'StateName');
        return view('guest.nurses.create', compact('states'));
    }

    public function store(NursesRequest $request)
    {
        $request->except('_token');

        $nurse = Nurses::create($request->all());

        $insurance = new NursesInsurance();
        $insurance->DocID = $nurse->DocID;
        $insurance->InsuranceID = Auth::user()->insurance->InsuranceID;
        $insurance->save();

        return redirect(route('nurses.index'))->with('success', 'New Nurse was successfully added!!!');
    }

    public function update(NursesRequest $request, $id)
    {

        $data = array_except($request->all(), ['_token']);
        $nurse = Nurses::where('DocID', $id)->update($data);

        return redirect(route('nurses.index'))->with('success', 'New Nurse was successfully updated!!!');
    }

    public function edit($id)
    {
        $nurse = Nurses::where('DocID', $id)->first();
        $states = State::pluck('StateName', 'StateName');
        return view('guest.nurses.edit', compact('nurse', 'states'));
    }

    public function delete($id)
    {
        $n_insurance = NursesInsurance::where('DocID', '=' ,$id)->first();
        if($n_insurance){
            $n_insurance->delete();
        }

        $nurse = Nurses::where('DocID', '=', $id)->first();
        if($nurse){
            $nurse->delete();
        }
        return response()->json(['success']);
    }
}

app/Http/Controllers/Guest/OrdersController.php
<?php

namespace App\Http\Controllers\Guest;

use App\Models\AuthItems;
use App\Models\Authorization;
use App\Models\Categories;
use App\Models\InsuranceMedGroup;
use App\Models\ItemCptMedGroup;
use App\Models\Nurses;
use App\Models\PatientAddress;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use PharIo\Manifest\AuthorTest;

class OrdersController extends Controller
{
    public function index()
    {
        $open = Authorization::where('IPAIsuranceID', Auth::user()->insurance->InsuranceID)->where('status', 'pending')->get();
        $closed = Authorization::where('IPAIsuranceID', Auth::user()->insurance->InsuranceID)->where('status', '!=' ,'pending')->get();
        return view('guest.orders.index', compact('open', 'closed'));
    }

    public function cancel($id)
    {
        $item = AuthItems::where('AuthID', $id)->first();
        if($item){
            $item->delete();
        }
        $order = Authorization::where('AuthID', $id)->first();
        if($order){
            $order->delete();
        }

        return redirect()->back()->with('Success', 'Order Cnaceled Successfully');
    }

    public function editOrder($id)
    {
        $order = Authorization::where('AuthID', $id)->first();

        $categories = Categories::all();
        $doctors = Nurses::orderBy('DocID', 'desc')->whereHas('patientDoctor', function ($query) use ($order) {
            $query->where('PatID', '=', $order->PatID);
        })->select(
            DB::raw("CONCAT(DocFirstName,' ',DocLastName) AS name"),'DocID')->pluck('name', 'DocID');

        $addresses = PatientAddress::where('PatID', $order->PatID)->select(
            DB::raw("CONCAT(Paddrname,': ',PAddress, ' ',Pcity, ' ', PState, ' ',PZip) AS address"),'PaddrID')->pluck('address', 'PaddrID');

        return view('guest.patients.delivery-edit', compact('categories', 'doctors', 'addresses', 'order'));
    }

    public function updateDelivery(Request $request, $id)
    {
        $order = Authorization::where('AuthID', $id)->first();
        $auth_items = AuthItems::where('AuthID', $id)->get();
        foreach ($auth_items as $item)
        {
            $item->delete();
        }

        $order->RefDocID = $request['PDoctor'];
        $order->save();

        $medGroup = InsuranceMedGroup::where('InsuranceID', Auth::user()->insurance->InsuranceID)->first();
        foreach ($request->all() as $key => $item) {
            $medgroupitem = ItemCptMedGroup::where('ItemID', $key)->where('medGroupID', $medGroup->medGroupID)->first();
            if ($medgroupitem) {
                $authitems = new AuthItems();
                $authitems->CPTDescription = $medgroupitem->CPTDescription;
                $authitems->CPTCode = $medgroupitem->CPTCode;
                $authitems->CPTCode2 = $medgroupitem->CPTCode2;
                $authitems->Qty = $item ? $item : 1;
                $authitems->AuthID = $id;
                $authitems->RentIndicator = $medgroupitem->RentIndicator;
                $authitems->FreqNumber = $medgroupitem->RentChargeFrequency;
                $authitems->FreqType = $medgroupitem->RentChargeFrequencyType;
                $authitems->save();
            }
        }

        return response()->json('success');

    }
}

app/Http/Controllers/Guest/ResourcesController.php
<?php

namespace App\Http\Controllers\Guest;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ResourcesController extends Controller
{
    public function index()
    {
        return view('guest.resources.index');
    }
}

resources/views/guest/customerCare/index.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('css/vendors/datatables/dataTables.bootstrap.css')}}"/>
    <link href="{{asset('css/pages/tables.css')}}" rel="stylesheet" type="text/css"/>
@endsection


@section('content')
    <aside class="right-side">
        <!-- Content Header (Page header) -->
        {{--<section class="content-header">--}}
            {{--<!--section starts-->--}}
            {{--<h1>Customer Care</h1>--}}
            {{--<ol class="breadcrumb">--}}
                {{--<li>--}}
                    {{--<a href="{{route('home')}}">--}}
                        {{--<i class="livicon" data-name="home" data-size="14" data-loop="true"></i> Dashboard--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="active">Customer Care</li>--}}
            {{--</ol>--}}
        {{--</section>--}}
        <!--section ends-->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN SAMPLE TABLE PORTLET-->
                    <div class="portlet box default">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="livicon" data-name="users" data-size="16" data-loop="true" data-c="#fff"
                                   data-hc="white"></i>
                            </div>

                            <div class="caption" style="float: right;">
                                <a href="#" data-toggle="modal" data-target="#modal-1"
                                   style="text-decoration: none;color: white;"><i class="livicon" data-name="plus-alt"
                                                                                  data-size="16" data-loop="true"
                                                                                  data-c="#fff" data-hc="white"></i>Create
                                    New Ticket</a>
                            </div>
                        </div>
                        <div class="portlet-body">

                        </div>
                    </div>
                    <!-- END SAMPLE TABLE PORTLET-->
                </div>
            </div>
            <div class="modal fade modal-fade-in-scale-up" tabindex="-1" id="modal-1" role="dialog"
                 aria-labelledby="modalLabelfade" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header bg-primary">
                            <h4 class="modal-title" id="modalLabelfade">Create New Ticket</h4>
                        </div>
                        <div class="modal-body">
                            <h3>
                                Are you filing a compliment or a concern?
                            </h3>
                            <div class="row">
                                <div class="col-md-2"></div>
                                <div class="col-md-10">
                                    <h5><a href="{{route('customer_care.create_compliment')}}">Compliment</a></h5>
                                    <h5><a href="{{route('customer_care.create_concern')}}">Concern</a></h5>
                                </div>
                                <div class="col-md-2"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- content -->
    </aside>
    <!-- right-side -->
@endsection

@section('scripts')
    <script type="text/javascript" src="{{asset('/js/vendors/datatables/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" src="{{asset('/js/vendors/datatables/dataTables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('/js/vendors/datatables/dataTables.responsive.js')}}"></script>
    <script src="{{asset('js/pages/table-responsive.js')}}"></script>
@endsection